# b5_weird_chars / all / count=2
# /picture-book-sup…-good-way-to-use/ ‎  (last_crawl=2025-12-09, source=404)
RewriteCond %{REQUEST_URI} ^/picture\-book\-sup%E2%80%A6\-good\-way\-to\-use/%20%E2%80%8E/?$ [NC]
RewriteRule ^ - [G,L]
# /recommended-pict…n-nursery-school/ ‎  (last_crawl=2025-10-13, source=404)
RewriteCond %{REQUEST_URI} ^/recommended\-pict%E2%80%A6n\-nursery\-school/%20%E2%80%8E/?$ [NC]
RewriteRule ^ - [G,L]
